version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies..."
      - echo "SOURCE_BRANCH is $SOURCE_BRANCH"
      - git clone --recurse-submodules -b $SOURCE_BRANCH https://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@github.com/Hussain-ADevOps/AD-Steering-Control 
      - pip install conan==1.60
  build:
    commands:

      - cd AD-Steering-Control
      # Run your build commands
      - .\.env\Build_jenkins_global.bat
artifacts:
  files:
    - '**/*'
  name: main_build
  discard-paths: no
